# Generated by Django 4.2.5 on 2023-10-19 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annee_scolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_annee', models.DateField()),
                ('fin_annee', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=35, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=55, unique=True)),
                ('durée', models.DateField()),
                ('classes', models.ManyToManyField(to='GSchoolApp.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.TextField(verbose_name='Lieu de naissance')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Numéro téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Nouveau', 'Nouveau élève'), ('Ancien', 'Ancien élève')], max_length=32)),
                ('date_inscription', models.DateField(default=True)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.classe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField()),
                ('coefficient', models.PositiveIntegerField()),
                ('classes', models.ManyToManyField(to='GSchoolApp.classe')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.domain')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=55, unique=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.annee_scolaire')),
                ('cycles', models.ManyToManyField(to='GSchoolApp.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pere', models.CharField(max_length=150, verbose_name='Nom du Père')),
                ('nom_mere', models.CharField(max_length=150, verbose_name='Nom de la Mère')),
                ('phone_number1', models.CharField(max_length=10)),
                ('phone_number2', models.CharField(max_length=10)),
                ('adresse', models.TextField()),
                ('eleves', models.ManyToManyField(to='GSchoolApp.eleve')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.matiere')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_d_evaluation', models.CharField(choices=[('Contrôle', 'Contrôle Continu'), ('Exam', 'Examen')], max_length=55)),
                ('note', models.FloatField()),
                ('jour', models.DateTimeField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.matiere')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=150, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.TextField(verbose_name='Lieu de naissance')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1)),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Numéro téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('poste', models.CharField(max_length=60)),
                ('type_poste', models.CharField(choices=[('Per', 'Permanent'), ('Vac', 'Vacataire')], max_length=60)),
                ('diplome', models.CharField(max_length=60)),
                ('specialite', models.CharField(max_length=70)),
                ('fonction', models.CharField(blank=True, max_length=60, null=True)),
                ('classes', models.ManyToManyField(to='GSchoolApp.classe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Emploi_du_temps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(max_length=60)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('date', models.DateField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.classe')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.FloatField(default=1.0)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.annee_scolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.eleve')),
                ('matieres', models.ManyToManyField(to='GSchoolApp.matiere')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.semestre')),
            ],
        ),
        migrations.AddField(
            model_name='annee_scolaire',
            name='cycles',
            field=models.ManyToManyField(to='GSchoolApp.cycle'),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('motif', models.CharField(max_length=200)),
                ('duree', models.DateTimeField()),
                ('eleves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GSchoolApp.eleve')),
            ],
        ),
    ]
